server:
  port: 8077
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  application:
    name: PROGMGR
  datasource:
    driver-class-name: "org.sqlite.JDBC"
    url: "jdbc:sqlite:progmgr.db"

mybatis:
  mapper-locations: "classpath:/mapper/*.xml"
  configuration:
    map-underscore-to-camel-case: true
